debug: :6060
listen: 127.0.0.1:6000
gateway: 127.0.0.1:8080
queue:
  drive: amqp
  option:
    url: amqp://guest:guest@localhost:5672/
filelog: ./logs
transfer:
  listen: 127.0.0.1:6001
  pipe: mq-subscriber